steps:
# Run tests
  - name: gradle:7.4.0-jdk17
    entrypoint: gradle
    args: [ 'test' ]
# Assemble packages
  - name: gradle:7.4.0-jdk17
    entrypoint: gradle
    args: [ 'assemble' ]
# Build with docker
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/idea-bot-323314/calendar_service:', '--build-arg=JAR_FILE=build/libs/calendarService.jar', '.' ]
images: [ 'gcr.io/idea-bot-323314/calendar-service' ]
# To store logs on Logging
options:
  logging: CLOUD_LOGGING_ONLY