steps:
  # Run tests
  - name: gradle:7.4.0-jdk17
    entrypoint: gradle
    args: [ 'test' ]
  # Assemble packages
  - name: gradle:7.4.0-jdk17
    entrypoint: gradle
    args: [ 'assemble' ]
  # Build with docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/calendar-service:$COMMIT_SHA','--build-arg=JAR_FILE=/build/libs/calendarService.jar','.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/calendar-service:$COMMIT_SHA' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'calendar-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/calendar-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
images: [ 'gcr.io/$PROJECT_ID/calendar-service:$COMMIT_SHA' ]
# To store logs on Logging
options:
  logging: CLOUD_LOGGING_ONLY