steps:
  - name: gradle:7.4.0-jdk17
    entrypoint: gradle
    args: [ 'test' ]
  - name: gradle:7.4.0-jdk17
    entrypoint: gradle
    args: [ 'assemble' ]
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/calendar_service:$COMMIT_SHA', '--build-arg=JAR_FILE=build/libs/calendarService.jar', '.' ]
images: [ 'gcr.io/$PROJECT_ID/calendar-service:$COMMIT_SHA' ]
# To store logs on Logging
options:
  logging: CLOUD_LOGGING_ONLY