---
spring:
  profiles:
    default: prod
server:
  port: 8080
  servlet:
    context-path: "/api"
  error:
    include-message: always
...
---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
name: dev-enviroment
environment: dev

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    config-url: http://localhost:8080/api/v1/api-docs/swagger-config
    url: http://localhost:8080/api/v1/api-docs
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    config-url: http://localhost:8080/api/v1/api-docs/swagger-config
    url: http://localhost:8080/api/v1/api-docs
    enabled: true

enabled: false
servers:
  - www.abc.com
  - www.xyz.com