---
spring:
  profiles:
    default: prod
server:
  port: 8080
  servlet:
    context-path: "/api"
  error:
    include-message: always
...

---
name: dev-enviroment
environment: dev
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    config-url: http://localhost:8080/api/v1/api-docs/swagger-config
    url: http://localhost:8080/api/v1/api-docs
    enabled: true

---
name: prod-enviroment
environment: production
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
  cloud:
    gcp:
      sql:
        instance-connection-name: ${CLOUD_SQL_CONNECTION_NAME}

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    config-url: http://localhost:8080/api/v1/api-docs/swagger-config
    url: http://localhost:8080/api/v1/api-docs
    enabled: true
